{
  "hash": "8957b06587a4803d3bbf99eea5a562bf",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Stage 11/13/14 · 坐标之争：σ 的大小序 vs 方向的功能序\"\nsubtitle: \"随机子空间训练 · 保谱 Shuffle-Rebuild · 布洛卡式损伤探针 · rank-1 原子重参数化\"\nauthor: \"math4mad\"\nformat:\n  html:\n    echo: true\n    warning: false\njupyter: python3\n---\n\n\n# 0. 命题\n\n> **数据科学要求特征值按大小排列，智能科学要求按功能方向排列。**\n> —— 项目笔记（2026-09-10），[`stage/stage11.md`](https://github.com/math4mad/Middle-Eigen-function/blob/multi-model/stage/stage11.md)\n\n前面所有阶段（A/B/C、等能量、TAIL/MID）都活在**第一个坐标**里：把矩阵 SVD、按 σ 从大到小排、\n然后按\"第几大\"切。本页用四个实验正面问：**这个坐标携带功能信息吗？携带多少？**\n\n# 1. 诊断：σ 序\"承重\"多少（保谱重排的期望改变量）\n\n`rel_perm = E_π ‖U diag(π(σ)) Vᵀ − W‖_F / ‖W‖_F`：保持奇异值多重集不变，只把 σ **随机重新配对**到方向上，\n矩阵会变多少（上限 √2）。谱越平 ⇒ 越小 ⇒ \"按大小切\"越接近\"随机切\"。\n\n::: {#5b5799de .cell execution_count=2}\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div id=\"niwpbkgavg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#niwpbkgavg table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#niwpbkgavg thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#niwpbkgavg p { margin: 0; padding: 0; }\n #niwpbkgavg .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 12px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #niwpbkgavg .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #niwpbkgavg .gt_title { color: #333333; font-size: 125%; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }\n #niwpbkgavg .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }\n #niwpbkgavg .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #niwpbkgavg .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #niwpbkgavg .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #niwpbkgavg .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #niwpbkgavg .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #niwpbkgavg .gt_column_spanner_outer:first-child { padding-left: 0; }\n #niwpbkgavg .gt_column_spanner_outer:last-child { padding-right: 0; }\n #niwpbkgavg .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #niwpbkgavg .gt_spanner_row { border-bottom-style: hidden; }\n #niwpbkgavg .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #niwpbkgavg .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #niwpbkgavg .gt_from_md> :first-child { margin-top: 0; }\n #niwpbkgavg .gt_from_md> :last-child { margin-bottom: 0; }\n #niwpbkgavg .gt_row { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #niwpbkgavg .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #niwpbkgavg .gt_indent_1 { text-indent: 5px; }\n #niwpbkgavg .gt_indent_2 { text-indent: calc(5px * 2); }\n #niwpbkgavg .gt_indent_3 { text-indent: calc(5px * 3); }\n #niwpbkgavg .gt_indent_4 { text-indent: calc(5px * 4); }\n #niwpbkgavg .gt_indent_5 { text-indent: calc(5px * 5); }\n #niwpbkgavg .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #niwpbkgavg .gt_row_group_first td { border-top-width: 2px; }\n #niwpbkgavg .gt_row_group_first th { border-top-width: 2px; }\n #niwpbkgavg .gt_striped { color: #333333; background-color: #F4F4F4; }\n #niwpbkgavg .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #niwpbkgavg .gt_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #niwpbkgavg .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #niwpbkgavg .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #niwpbkgavg .gt_grand_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #niwpbkgavg .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #niwpbkgavg .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #niwpbkgavg .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #niwpbkgavg .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #niwpbkgavg .gt_left { text-align: left; }\n #niwpbkgavg .gt_center { text-align: center; }\n #niwpbkgavg .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #niwpbkgavg .gt_font_normal { font-weight: normal; }\n #niwpbkgavg .gt_font_bold { font-weight: bold; }\n #niwpbkgavg .gt_font_italic { font-style: italic; }\n #niwpbkgavg .gt_super { font-size: 65%; }\n #niwpbkgavg .gt_footnotes { color: font-color(#FFFFFF); background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #niwpbkgavg .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #niwpbkgavg .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #niwpbkgavg .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #niwpbkgavg .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #niwpbkgavg .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"7\" class=\"gt_heading gt_title gt_font_normal\">排序位置携带的信息量：按矩阵类型</td>\n  </tr>\n  <tr class=\"gt_heading\">\n    <td colspan=\"7\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\">本项目 stage1–12 的所有切割实验都落在 rel_perm 最低的 mlp.down_proj 上</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"模型\">模型</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"矩阵\">矩阵</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"shape\">shape</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rel_perm\">rel_perm</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cv\">cv</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"top10%σ-能量\">top10%σ 能量</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cond\">cond</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">Qwen2.5-0.5B</td>\n    <td class=\"gt_row gt_left\">q_proj</td>\n    <td class=\"gt_row gt_left\">896×896</td>\n    <td class=\"gt_row gt_right\">1.041</td>\n    <td class=\"gt_row gt_right\">1.17</td>\n    <td class=\"gt_row gt_right\">0.63</td>\n    <td class=\"gt_row gt_right\">268518</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Qwen2.5-1.5B</td>\n    <td class=\"gt_row gt_left\">q_proj</td>\n    <td class=\"gt_row gt_left\">1536×1536</td>\n    <td class=\"gt_row gt_right\">1.014</td>\n    <td class=\"gt_row gt_right\">1.04</td>\n    <td class=\"gt_row gt_right\">0.6</td>\n    <td class=\"gt_row gt_right\">80420</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Qwen2.5-0.5B</td>\n    <td class=\"gt_row gt_left\">o_proj</td>\n    <td class=\"gt_row gt_left\">896×896</td>\n    <td class=\"gt_row gt_right\">0.988</td>\n    <td class=\"gt_row gt_right\">0.99</td>\n    <td class=\"gt_row gt_right\">0.54</td>\n    <td class=\"gt_row gt_right\">33355</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Qwen2.5-1.5B</td>\n    <td class=\"gt_row gt_left\">o_proj</td>\n    <td class=\"gt_row gt_left\">1536×1536</td>\n    <td class=\"gt_row gt_right\">0.916</td>\n    <td class=\"gt_row gt_right\">0.86</td>\n    <td class=\"gt_row gt_right\">0.47</td>\n    <td class=\"gt_row gt_right\">366019</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">roberta-base</td>\n    <td class=\"gt_row gt_left\">attention.output.dense</td>\n    <td class=\"gt_row gt_left\">768×768</td>\n    <td class=\"gt_row gt_right\">0.849</td>\n    <td class=\"gt_row gt_right\">0.76</td>\n    <td class=\"gt_row gt_right\">0.41</td>\n    <td class=\"gt_row gt_right\">20438</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">bert-base</td>\n    <td class=\"gt_row gt_left\">attention.output.dense</td>\n    <td class=\"gt_row gt_left\">768×768</td>\n    <td class=\"gt_row gt_right\">0.824</td>\n    <td class=\"gt_row gt_right\">0.72</td>\n    <td class=\"gt_row gt_right\">0.39</td>\n    <td class=\"gt_row gt_right\">39029</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">roberta-base</td>\n    <td class=\"gt_row gt_left\">output.dense</td>\n    <td class=\"gt_row gt_left\">768×768</td>\n    <td class=\"gt_row gt_right\">0.722</td>\n    <td class=\"gt_row gt_right\">0.61</td>\n    <td class=\"gt_row gt_right\">0.36</td>\n    <td class=\"gt_row gt_right\">13455</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">bert-base</td>\n    <td class=\"gt_row gt_left\">output.dense</td>\n    <td class=\"gt_row gt_left\">768×768</td>\n    <td class=\"gt_row gt_right\">0.689</td>\n    <td class=\"gt_row gt_right\">0.58</td>\n    <td class=\"gt_row gt_right\">0.35</td>\n    <td class=\"gt_row gt_right\">1854</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">roberta-base</td>\n    <td class=\"gt_row gt_left\">intermediate.dense</td>\n    <td class=\"gt_row gt_left\">3072×768</td>\n    <td class=\"gt_row gt_right\">0.627</td>\n    <td class=\"gt_row gt_right\">0.49</td>\n    <td class=\"gt_row gt_right\">0.35</td>\n    <td class=\"gt_row gt_right\">145</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">bert-base</td>\n    <td class=\"gt_row gt_left\">intermediate.dense</td>\n    <td class=\"gt_row gt_left\">3072×768</td>\n    <td class=\"gt_row gt_right\">0.567</td>\n    <td class=\"gt_row gt_right\">0.44</td>\n    <td class=\"gt_row gt_right\">0.32</td>\n    <td class=\"gt_row gt_right\">34</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Qwen2.5-1.5B</td>\n    <td class=\"gt_row gt_left\">mlp.gate_proj</td>\n    <td class=\"gt_row gt_left\">8960×1536</td>\n    <td class=\"gt_row gt_right\">0.489</td>\n    <td class=\"gt_row gt_right\">0.37</td>\n    <td class=\"gt_row gt_right\">0.28</td>\n    <td class=\"gt_row gt_right\">25</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Qwen2.5-0.5B</td>\n    <td class=\"gt_row gt_left\">mlp.gate_proj</td>\n    <td class=\"gt_row gt_left\">4864×896</td>\n    <td class=\"gt_row gt_right\">0.487</td>\n    <td class=\"gt_row gt_right\">0.37</td>\n    <td class=\"gt_row gt_right\">0.27</td>\n    <td class=\"gt_row gt_right\">14</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Qwen2.5-0.5B</td>\n    <td class=\"gt_row gt_left\">mlp.down_proj</td>\n    <td class=\"gt_row gt_left\">896×4864</td>\n    <td class=\"gt_row gt_right\">0.472</td>\n    <td class=\"gt_row gt_right\">0.36</td>\n    <td class=\"gt_row gt_right\">0.25</td>\n    <td class=\"gt_row gt_right\">16</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">Qwen2.5-1.5B</td>\n    <td class=\"gt_row gt_left\">mlp.down_proj</td>\n    <td class=\"gt_row gt_left\">1536×8960</td>\n    <td class=\"gt_row gt_right\">0.447</td>\n    <td class=\"gt_row gt_right\">0.33</td>\n    <td class=\"gt_row gt_right\">0.25</td>\n    <td class=\"gt_row gt_right\">18</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n:::\n\n\n![](/figs/steepness.png)\n\n**一次性解释本项目最大的不一致**：stage5 里 BERT 全参微调的等能量位置残差 **+0.080**，\n而 Qwen+LoRA 只有 **+0.015（噪声内）**。原因不是\"模型大小\"或\"微调方式\"，而是**矩阵类型**：\n注意力矩阵 rel_perm ≈ 0.82–1.04（top10% 占 54–63% 能量），MLP `down_proj` 只有 0.45–0.49\n（top10% 占 25%）。**在平坦谱上，\"第几大\"本来就没多少信息可携带。**\n\n# 2. 实验 A：随机子空间训练（RS-LoRA）——取向重要吗？\n\n把 LoRA 的输入投影 A 换成**固定的 Haar 随机正交基**、只训 B ⇒ 更新被限制在随机抽的 d 维子空间里，\n与 SVD 排序无关。参数量与控制组可比。\n\n::: {#f01d9d82 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div id=\"vxunhdgzkv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#vxunhdgzkv table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#vxunhdgzkv thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#vxunhdgzkv p { margin: 0; padding: 0; }\n #vxunhdgzkv .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 12px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #vxunhdgzkv .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #vxunhdgzkv .gt_title { color: #333333; font-size: 125%; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }\n #vxunhdgzkv .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }\n #vxunhdgzkv .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #vxunhdgzkv .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #vxunhdgzkv .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #vxunhdgzkv .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #vxunhdgzkv .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #vxunhdgzkv .gt_column_spanner_outer:first-child { padding-left: 0; }\n #vxunhdgzkv .gt_column_spanner_outer:last-child { padding-right: 0; }\n #vxunhdgzkv .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #vxunhdgzkv .gt_spanner_row { border-bottom-style: hidden; }\n #vxunhdgzkv .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #vxunhdgzkv .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #vxunhdgzkv .gt_from_md> :first-child { margin-top: 0; }\n #vxunhdgzkv .gt_from_md> :last-child { margin-bottom: 0; }\n #vxunhdgzkv .gt_row { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #vxunhdgzkv .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #vxunhdgzkv .gt_indent_1 { text-indent: 5px; }\n #vxunhdgzkv .gt_indent_2 { text-indent: calc(5px * 2); }\n #vxunhdgzkv .gt_indent_3 { text-indent: calc(5px * 3); }\n #vxunhdgzkv .gt_indent_4 { text-indent: calc(5px * 4); }\n #vxunhdgzkv .gt_indent_5 { text-indent: calc(5px * 5); }\n #vxunhdgzkv .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #vxunhdgzkv .gt_row_group_first td { border-top-width: 2px; }\n #vxunhdgzkv .gt_row_group_first th { border-top-width: 2px; }\n #vxunhdgzkv .gt_striped { color: #333333; background-color: #F4F4F4; }\n #vxunhdgzkv .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #vxunhdgzkv .gt_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #vxunhdgzkv .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #vxunhdgzkv .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #vxunhdgzkv .gt_grand_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #vxunhdgzkv .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #vxunhdgzkv .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #vxunhdgzkv .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #vxunhdgzkv .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #vxunhdgzkv .gt_left { text-align: left; }\n #vxunhdgzkv .gt_center { text-align: center; }\n #vxunhdgzkv .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #vxunhdgzkv .gt_font_normal { font-weight: normal; }\n #vxunhdgzkv .gt_font_bold { font-weight: bold; }\n #vxunhdgzkv .gt_font_italic { font-style: italic; }\n #vxunhdgzkv .gt_super { font-size: 65%; }\n #vxunhdgzkv .gt_footnotes { color: font-color(#FFFFFF); background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #vxunhdgzkv .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #vxunhdgzkv .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #vxunhdgzkv .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #vxunhdgzkv .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #vxunhdgzkv .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"9\" class=\"gt_heading gt_title gt_font_normal\">Stage 11 各组（0.5B + RTE 10% + LoRA 协议）</td>\n  </tr>\n  <tr class=\"gt_heading\">\n    <td colspan=\"9\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\">控制组 = 同一协议下 stage9/10 的 LoRA baseline（seed1 0.556, seed2 0.588）；噪声带 ±0.03</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"组\">组</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"类型\">类型</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m/d\">m/d</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"可学参数\">可学参数</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"best-dev\">best dev</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Δ-vs-LoRA-控制\">Δ vs LoRA 控制</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"seed\">seed</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"末3ep-dev\">末3ep dev</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"final-dev-loss\">final dev loss</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">RS10_s1</td>\n    <td class=\"gt_row gt_left\">rs</td>\n    <td class=\"gt_row gt_left\">10</td>\n    <td class=\"gt_row gt_right\">3,043,072</td>\n    <td class=\"gt_row gt_right\">0.538</td>\n    <td class=\"gt_row gt_right\">-0.018</td>\n    <td class=\"gt_row gt_right\">1</td>\n    <td class=\"gt_row gt_right\">0.527</td>\n    <td class=\"gt_row gt_right\">1.17</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">RS10_s2</td>\n    <td class=\"gt_row gt_left\">rs</td>\n    <td class=\"gt_row gt_left\">10</td>\n    <td class=\"gt_row gt_right\">3,043,072</td>\n    <td class=\"gt_row gt_right\">0.549</td>\n    <td class=\"gt_row gt_right\">-0.039</td>\n    <td class=\"gt_row gt_right\">2</td>\n    <td class=\"gt_row gt_right\">0.538</td>\n    <td class=\"gt_row gt_right\">1.02</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">SHUFb_s1</td>\n    <td class=\"gt_row gt_left\">shuf</td>\n    <td class=\"gt_row gt_left\">b</td>\n    <td class=\"gt_row gt_right\">4,400,896</td>\n    <td class=\"gt_row gt_right\">0.545</td>\n    <td class=\"gt_row gt_right\">-0.011</td>\n    <td class=\"gt_row gt_right\">1</td>\n    <td class=\"gt_row gt_right\">0.538</td>\n    <td class=\"gt_row gt_right\">1.38</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">SHUFb_s2</td>\n    <td class=\"gt_row gt_left\">shuf</td>\n    <td class=\"gt_row gt_left\">b</td>\n    <td class=\"gt_row gt_right\">4,400,896</td>\n    <td class=\"gt_row gt_right\">0.563</td>\n    <td class=\"gt_row gt_right\">-0.025</td>\n    <td class=\"gt_row gt_right\">2</td>\n    <td class=\"gt_row gt_right\">0.533</td>\n    <td class=\"gt_row gt_right\">1.2</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">SHUFg_s1</td>\n    <td class=\"gt_row gt_left\">shuf</td>\n    <td class=\"gt_row gt_left\">g</td>\n    <td class=\"gt_row gt_right\">4,400,896</td>\n    <td class=\"gt_row gt_right\">0.552</td>\n    <td class=\"gt_row gt_right\">-0.004</td>\n    <td class=\"gt_row gt_right\">1</td>\n    <td class=\"gt_row gt_right\">0.534</td>\n    <td class=\"gt_row gt_right\">1.33</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">SHUFg_s2</td>\n    <td class=\"gt_row gt_left\">shuf</td>\n    <td class=\"gt_row gt_left\">g</td>\n    <td class=\"gt_row gt_right\">4,400,896</td>\n    <td class=\"gt_row gt_right\">0.498</td>\n    <td class=\"gt_row gt_right\">-0.09</td>\n    <td class=\"gt_row gt_right\">2</td>\n    <td class=\"gt_row gt_right\">0.481</td>\n    <td class=\"gt_row gt_right\">1.48</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">lora_s1</td>\n    <td class=\"gt_row gt_left\">lora</td>\n    <td class=\"gt_row gt_left\"><NA></td>\n    <td class=\"gt_row gt_right\">4,400,896</td>\n    <td class=\"gt_row gt_right\">0.556</td>\n    <td class=\"gt_row gt_right\">-0.0</td>\n    <td class=\"gt_row gt_right\">1</td>\n    <td class=\"gt_row gt_right\">0.538</td>\n    <td class=\"gt_row gt_right\">1.13</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">lora_s2</td>\n    <td class=\"gt_row gt_left\">lora</td>\n    <td class=\"gt_row gt_left\"><NA></td>\n    <td class=\"gt_row gt_right\">4,400,896</td>\n    <td class=\"gt_row gt_right\">0.588</td>\n    <td class=\"gt_row gt_right\">0.0</td>\n    <td class=\"gt_row gt_right\">2</td>\n    <td class=\"gt_row gt_right\">0.566</td>\n    <td class=\"gt_row gt_right\">1.04</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n:::\n\n\n# 3. 实验 B：Shuffle-Rebuild —— **保持整个谱不变**，只打乱\"方向↔大小\"的配对\n\n$$W=U\\,\\mathrm{diag}(\\sigma)\\,V^\\top\\ \\longrightarrow\\ W'=U\\,\\mathrm{diag}(\\pi(\\sigma))\\,V^\\top$$\n\n这是比\"切割\"强得多的配平：**σ 多重集、能量分布、Frobenius 范数、秩全部逐位不变**，\n唯一被改变的就是\"排序位置\"。所以任何性能变化都只能归因于**顺序本身有没有含义**。\n\n\n\n::: {#b728de27 .cell execution_count=5}\n\n::: {.cell-output .cell-output-stdout}\n```\n读法（seed1，控制组 0.556）：带内置换 dev=0.545（Δ-0.011），全局置换 dev=0.552（Δ-0.004）。两者全部落在 ±0.030 噪声带内。\n干预强度（由 §1 的 rel_perm 直接给出）：down_proj 全局重排会改变矩阵 ≈0.46 的 Frobenius 质量（带内置换 ≈0.05）⇒ 这不是一个弱干预。\n```\n:::\n:::\n\n\n:::{.callout-warning title=\"本轮修掉的一个真 bug（只影响诊断字段，不影响结论）\"}\n`Tensor.numpy()` 在 CPU 张量上**共享内存**：`W = mod.weight...numpy()` 之后再执行\n`mod.weight.copy_(W_new)`，`W` 的内容会**静默变成新权重** —— 于是所有历史结果里的\n`backfill_gap`（\"这次消融把矩阵改了多少\"）都被记成了 **0.0**（stage5 / stage9 / stage10 全部如此）。\n消融本身是**正确执行**的（SVD 在 copy_ 之前完成、重构矩阵被正确写回），只是这个诊断字段无效。\n已在 `stage3_llm_lora.py` / `stage11_random_subspace.py` / `two_orderings.py` 三处加 `.copy()` 修正。\n**真实值可直接推出**：只把若干 σ 置零时 $\\Vert W-W'\\Vert_F^2=\\sum_{\\text{dropped}}\\sigma_i^2$，\n故 rel_change $=\\sqrt{1-\\text{energy\\_kept}}$；stage9 的 TAIL6 是 $\\sqrt{1-0.775}\\approx\\mathbf{0.47}$\n（每层被削掉 47% 的 Frobenius 质量）—— 这个量级以前被 0.0 掩盖了。\n:::\n\n# 4. 实验 C：布洛卡式损伤探针 —— 直接量两套排序的一致性 τ\n\n零训练前向：把单个 rank-1 分量 $W\\leftarrow W-\\sigma_i u_i v_i^\\top$ 拿掉，\n量 RTE 文本上因果语言建模损失的变化 Δloss ⇒ **功能序**；再与 **σ 序**算 Kendall τ。\n\n::: {#08159a15 .cell execution_count=6}\n\n::: {.cell-output .cell-output-stdout}\n```\nMLP down_proj 各分位带 Δloss（1=最大σ带 → 10=最小σ带）：\n  +0.319  +0.051  +0.033  +0.035  +0.024  +0.027  +0.023  +0.012  +0.013  +0.008\n注意力 q_proj 各分位带 Δloss：\n  +0.057  +0.002  -0.000  +0.000  -0.000  +0.000  -0.000  -0.000  -0.000  -0.000\nτ 均值：MLP down_proj = -0.22，注意力 q_proj = -0.12 ⇒ 两类矩阵上 σ 序都不预测功能序（尽管 q_proj 的谱陡峭度 rel_perm≈1.0 远高于 down_proj≈0.47）\n```\n:::\n:::\n\n\n![](/figs/two_orderings.png)\n\n# 5. 实验 D（预注册，`stage/stage14.md`）：rank-1 原子重参数化\n\n把注意力矩阵的**方向全部冻结**，只留原子系数：$W(\\delta)=W_0+U_m\\,\\mathrm{diag}(\\delta\\odot\\sigma_m)\\,V_m^\\top$，\n并用**同容量的 Haar 随机基**做严格对照：\n\n| 组 | 基 | 每矩阵可学标量 | 全模型可学参数 |\n|---|---|---|---|\n| `ATOM64` | SVD 原子 top-64 | 64 | ~7.9k |\n| `RAND64` | 随机正交基 | 64 | ~7.9k |\n| `ATOMfull` | 全部 896 个原子 | 896 | ~88k |\n| `lora8` | 两端都可学 | — | 4.4M（控制） |\n\n**预注册预言**（写在这里再跑）：\n1. 若 σ 序 = 功能序的可用代理 ⇒ `ATOM64` ≫ `RAND64`（同容量不同基）；\n2. 若 `ATOM64` ≈ `lora8`（**550 倍**少的参数）⇒ 小样本微调主要是\"重新加权已有原子\"，不需要新方向；\n3. 若 `ATOM64+L8` > `ATOM64` ⇒ 微调必须引入**谱外新方向**（\"入侵维度\"存在）。\n   结合 §1（注意力 rel_perm≈1.0，MLP 0.47）**定向预言**：ATOM 的优势应出现在注意力，\n   在 `mlp.down_proj` 上 ATOM≈RAND。\n\n::: {#94ff50c0 .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div id=\"vsbwmanpcc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#vsbwmanpcc table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#vsbwmanpcc thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#vsbwmanpcc p { margin: 0; padding: 0; }\n #vsbwmanpcc .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 12px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #vsbwmanpcc .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #vsbwmanpcc .gt_title { color: #333333; font-size: 125%; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }\n #vsbwmanpcc .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }\n #vsbwmanpcc .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #vsbwmanpcc .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #vsbwmanpcc .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #vsbwmanpcc .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #vsbwmanpcc .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #vsbwmanpcc .gt_column_spanner_outer:first-child { padding-left: 0; }\n #vsbwmanpcc .gt_column_spanner_outer:last-child { padding-right: 0; }\n #vsbwmanpcc .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #vsbwmanpcc .gt_spanner_row { border-bottom-style: hidden; }\n #vsbwmanpcc .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #vsbwmanpcc .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #vsbwmanpcc .gt_from_md> :first-child { margin-top: 0; }\n #vsbwmanpcc .gt_from_md> :last-child { margin-bottom: 0; }\n #vsbwmanpcc .gt_row { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #vsbwmanpcc .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #vsbwmanpcc .gt_indent_1 { text-indent: 5px; }\n #vsbwmanpcc .gt_indent_2 { text-indent: calc(5px * 2); }\n #vsbwmanpcc .gt_indent_3 { text-indent: calc(5px * 3); }\n #vsbwmanpcc .gt_indent_4 { text-indent: calc(5px * 4); }\n #vsbwmanpcc .gt_indent_5 { text-indent: calc(5px * 5); }\n #vsbwmanpcc .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #vsbwmanpcc .gt_row_group_first td { border-top-width: 2px; }\n #vsbwmanpcc .gt_row_group_first th { border-top-width: 2px; }\n #vsbwmanpcc .gt_striped { color: #333333; background-color: #F4F4F4; }\n #vsbwmanpcc .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #vsbwmanpcc .gt_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #vsbwmanpcc .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #vsbwmanpcc .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #vsbwmanpcc .gt_grand_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #vsbwmanpcc .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #vsbwmanpcc .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #vsbwmanpcc .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #vsbwmanpcc .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #vsbwmanpcc .gt_left { text-align: left; }\n #vsbwmanpcc .gt_center { text-align: center; }\n #vsbwmanpcc .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #vsbwmanpcc .gt_font_normal { font-weight: normal; }\n #vsbwmanpcc .gt_font_bold { font-weight: bold; }\n #vsbwmanpcc .gt_font_italic { font-style: italic; }\n #vsbwmanpcc .gt_super { font-size: 65%; }\n #vsbwmanpcc .gt_footnotes { color: font-color(#FFFFFF); background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #vsbwmanpcc .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #vsbwmanpcc .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #vsbwmanpcc .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #vsbwmanpcc .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #vsbwmanpcc .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"8\" class=\"gt_heading gt_title gt_font_normal\">实验 D：注意力 + MLP 一起（120 个矩阵，含自带 LoRA 控制组）（0.5B + RTE 10%，控制组 = LoRA r=8，4.4M 参数，dev 0.556）</td>\n  </tr>\n  <tr class=\"gt_heading\">\n    <td colspan=\"8\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\">方向全部冻结、只学原子系数 δ（无量纲相对重标，lr=1e-2；分类头 2e-4）</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"组\">组</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"基\">基</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m\">m</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"可学参数\">可学参数</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"best-dev\">best dev</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Δ-vs-LoRA8-控制\">Δ vs LoRA8 控制</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"final-train-acc\">final train acc</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"final-dev-loss\">final dev loss</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">ATOM64_s1</td>\n    <td class=\"gt_row gt_left\">SVD 原子</td>\n    <td class=\"gt_row gt_right\">64.0</td>\n    <td class=\"gt_row gt_right\">9,472</td>\n    <td class=\"gt_row gt_right\">0.531</td>\n    <td class=\"gt_row gt_right\">-0.025</td>\n    <td class=\"gt_row gt_right\">0.996</td>\n    <td class=\"gt_row gt_right\">1.18</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">ATOMfull_s1</td>\n    <td class=\"gt_row gt_left\">SVD 原子</td>\n    <td class=\"gt_row gt_right\">896.0</td>\n    <td class=\"gt_row gt_right\">72,448</td>\n    <td class=\"gt_row gt_right\">0.578</td>\n    <td class=\"gt_row gt_right\">0.022</td>\n    <td class=\"gt_row gt_right\">1.0</td>\n    <td class=\"gt_row gt_right\">1.84</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">RAND64_s1</td>\n    <td class=\"gt_row gt_left\">随机正交基</td>\n    <td class=\"gt_row gt_right\">64.0</td>\n    <td class=\"gt_row gt_right\">9,472</td>\n    <td class=\"gt_row gt_right\">0.542</td>\n    <td class=\"gt_row gt_right\">-0.014</td>\n    <td class=\"gt_row gt_right\">0.984</td>\n    <td class=\"gt_row gt_right\">1.28</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">lora_s1</td>\n    <td class=\"gt_row gt_left\">两端可学</td>\n    <td class=\"gt_row gt_right\"><NA></td>\n    <td class=\"gt_row gt_right\">4,400,896</td>\n    <td class=\"gt_row gt_right\">0.556</td>\n    <td class=\"gt_row gt_right\">-0.0</td>\n    <td class=\"gt_row gt_right\">0.908</td>\n    <td class=\"gt_row gt_right\">1.13</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div id=\"fsnwhlubzp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#fsnwhlubzp table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#fsnwhlubzp thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#fsnwhlubzp p { margin: 0; padding: 0; }\n #fsnwhlubzp .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 12px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #fsnwhlubzp .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #fsnwhlubzp .gt_title { color: #333333; font-size: 125%; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }\n #fsnwhlubzp .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }\n #fsnwhlubzp .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #fsnwhlubzp .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #fsnwhlubzp .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #fsnwhlubzp .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #fsnwhlubzp .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #fsnwhlubzp .gt_column_spanner_outer:first-child { padding-left: 0; }\n #fsnwhlubzp .gt_column_spanner_outer:last-child { padding-right: 0; }\n #fsnwhlubzp .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #fsnwhlubzp .gt_spanner_row { border-bottom-style: hidden; }\n #fsnwhlubzp .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #fsnwhlubzp .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #fsnwhlubzp .gt_from_md> :first-child { margin-top: 0; }\n #fsnwhlubzp .gt_from_md> :last-child { margin-bottom: 0; }\n #fsnwhlubzp .gt_row { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #fsnwhlubzp .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #fsnwhlubzp .gt_indent_1 { text-indent: 5px; }\n #fsnwhlubzp .gt_indent_2 { text-indent: calc(5px * 2); }\n #fsnwhlubzp .gt_indent_3 { text-indent: calc(5px * 3); }\n #fsnwhlubzp .gt_indent_4 { text-indent: calc(5px * 4); }\n #fsnwhlubzp .gt_indent_5 { text-indent: calc(5px * 5); }\n #fsnwhlubzp .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #fsnwhlubzp .gt_row_group_first td { border-top-width: 2px; }\n #fsnwhlubzp .gt_row_group_first th { border-top-width: 2px; }\n #fsnwhlubzp .gt_striped { color: #333333; background-color: #F4F4F4; }\n #fsnwhlubzp .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #fsnwhlubzp .gt_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #fsnwhlubzp .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #fsnwhlubzp .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #fsnwhlubzp .gt_grand_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #fsnwhlubzp .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #fsnwhlubzp .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #fsnwhlubzp .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #fsnwhlubzp .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #fsnwhlubzp .gt_left { text-align: left; }\n #fsnwhlubzp .gt_center { text-align: center; }\n #fsnwhlubzp .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #fsnwhlubzp .gt_font_normal { font-weight: normal; }\n #fsnwhlubzp .gt_font_bold { font-weight: bold; }\n #fsnwhlubzp .gt_font_italic { font-style: italic; }\n #fsnwhlubzp .gt_super { font-size: 65%; }\n #fsnwhlubzp .gt_footnotes { color: font-color(#FFFFFF); background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #fsnwhlubzp .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #fsnwhlubzp .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #fsnwhlubzp .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #fsnwhlubzp .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #fsnwhlubzp .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"8\" class=\"gt_heading gt_title gt_font_normal\">实验 D：只注意力（96 个矩阵）（0.5B + RTE 10%，控制组 = LoRA r=8，4.4M 参数，dev 0.556）</td>\n  </tr>\n  <tr class=\"gt_heading\">\n    <td colspan=\"8\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\">方向全部冻结、只学原子系数 δ（无量纲相对重标，lr=1e-2；分类头 2e-4）</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"组\">组</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"基\">基</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m\">m</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"可学参数\">可学参数</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"best-dev\">best dev</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Δ-vs-LoRA8-控制\">Δ vs LoRA8 控制</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"final-train-acc\">final train acc</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"final-dev-loss\">final dev loss</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">ATOM64_L8_s1</td>\n    <td class=\"gt_row gt_left\">SVD 原子</td>\n    <td class=\"gt_row gt_right\">64</td>\n    <td class=\"gt_row gt_right\">1,089,280</td>\n    <td class=\"gt_row gt_right\">0.523</td>\n    <td class=\"gt_row gt_right\">-0.033</td>\n    <td class=\"gt_row gt_right\">0.956</td>\n    <td class=\"gt_row gt_right\">1.46</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">ATOM64_s1</td>\n    <td class=\"gt_row gt_left\">SVD 原子</td>\n    <td class=\"gt_row gt_right\">64</td>\n    <td class=\"gt_row gt_right\">7,936</td>\n    <td class=\"gt_row gt_right\">0.523</td>\n    <td class=\"gt_row gt_right\">-0.033</td>\n    <td class=\"gt_row gt_right\">0.992</td>\n    <td class=\"gt_row gt_right\">1.24</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">ATOMfull_s1</td>\n    <td class=\"gt_row gt_left\">SVD 原子</td>\n    <td class=\"gt_row gt_right\">896</td>\n    <td class=\"gt_row gt_right\">50,944</td>\n    <td class=\"gt_row gt_right\">0.563</td>\n    <td class=\"gt_row gt_right\">0.007</td>\n    <td class=\"gt_row gt_right\">1.0</td>\n    <td class=\"gt_row gt_right\">1.57</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">RAND64_s1</td>\n    <td class=\"gt_row gt_left\">随机正交基</td>\n    <td class=\"gt_row gt_right\">64</td>\n    <td class=\"gt_row gt_right\">7,936</td>\n    <td class=\"gt_row gt_right\">0.531</td>\n    <td class=\"gt_row gt_right\">-0.025</td>\n    <td class=\"gt_row gt_right\">0.988</td>\n    <td class=\"gt_row gt_right\">1.24</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div id=\"uanbfjvzrv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>\n#uanbfjvzrv table {\n          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n        }\n\n#uanbfjvzrv thead, tbody, tfoot, tr, td, th { border-style: none; }\n tr { background-color: transparent; }\n#uanbfjvzrv p { margin: 0; padding: 0; }\n #uanbfjvzrv .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 12px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }\n #uanbfjvzrv .gt_caption { padding-top: 4px; padding-bottom: 4px; }\n #uanbfjvzrv .gt_title { color: #333333; font-size: 125%; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }\n #uanbfjvzrv .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }\n #uanbfjvzrv .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #uanbfjvzrv .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #uanbfjvzrv .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }\n #uanbfjvzrv .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }\n #uanbfjvzrv .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }\n #uanbfjvzrv .gt_column_spanner_outer:first-child { padding-left: 0; }\n #uanbfjvzrv .gt_column_spanner_outer:last-child { padding-right: 0; }\n #uanbfjvzrv .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }\n #uanbfjvzrv .gt_spanner_row { border-bottom-style: hidden; }\n #uanbfjvzrv .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }\n #uanbfjvzrv .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }\n #uanbfjvzrv .gt_from_md> :first-child { margin-top: 0; }\n #uanbfjvzrv .gt_from_md> :last-child { margin-bottom: 0; }\n #uanbfjvzrv .gt_row { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }\n #uanbfjvzrv .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }\n #uanbfjvzrv .gt_indent_1 { text-indent: 5px; }\n #uanbfjvzrv .gt_indent_2 { text-indent: calc(5px * 2); }\n #uanbfjvzrv .gt_indent_3 { text-indent: calc(5px * 3); }\n #uanbfjvzrv .gt_indent_4 { text-indent: calc(5px * 4); }\n #uanbfjvzrv .gt_indent_5 { text-indent: calc(5px * 5); }\n #uanbfjvzrv .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }\n #uanbfjvzrv .gt_row_group_first td { border-top-width: 2px; }\n #uanbfjvzrv .gt_row_group_first th { border-top-width: 2px; }\n #uanbfjvzrv .gt_striped { color: #333333; background-color: #F4F4F4; }\n #uanbfjvzrv .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #uanbfjvzrv .gt_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #uanbfjvzrv .gt_first_summary_row { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; }\n #uanbfjvzrv .gt_last_summary_row_top { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }\n #uanbfjvzrv .gt_grand_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }\n #uanbfjvzrv .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }\n #uanbfjvzrv .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }\n #uanbfjvzrv .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #uanbfjvzrv .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #uanbfjvzrv .gt_left { text-align: left; }\n #uanbfjvzrv .gt_center { text-align: center; }\n #uanbfjvzrv .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n #uanbfjvzrv .gt_font_normal { font-weight: normal; }\n #uanbfjvzrv .gt_font_bold { font-weight: bold; }\n #uanbfjvzrv .gt_font_italic { font-style: italic; }\n #uanbfjvzrv .gt_super { font-size: 65%; }\n #uanbfjvzrv .gt_footnotes { color: font-color(#FFFFFF); background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #uanbfjvzrv .gt_footnote { margin: 0px; font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; }\n #uanbfjvzrv .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }\n #uanbfjvzrv .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }\n #uanbfjvzrv .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }\n #uanbfjvzrv .gt_asterisk { font-size: 100%; vertical-align: 0; }\n \n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n<thead>\n\n  <tr class=\"gt_heading\">\n    <td colspan=\"8\" class=\"gt_heading gt_title gt_font_normal\">实验 D：只 MLP（72 个矩阵，rel_perm 0.47 那一类）（0.5B + RTE 10%，控制组 = LoRA r=8，4.4M 参数，dev 0.556）</td>\n  </tr>\n  <tr class=\"gt_heading\">\n    <td colspan=\"8\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\">方向全部冻结、只学原子系数 δ（无量纲相对重标，lr=1e-2；分类头 2e-4）</td>\n  </tr>\n<tr class=\"gt_col_headings\">\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"组\">组</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"基\">基</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m\">m</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"可学参数\">可学参数</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"best-dev\">best dev</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Δ-vs-LoRA8-控制\">Δ vs LoRA8 控制</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"final-train-acc\">final train acc</th>\n  <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"final-dev-loss\">final dev loss</th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n  <tr>\n    <td class=\"gt_row gt_left\">ATOM64_L8_s1</td>\n    <td class=\"gt_row gt_left\">SVD 原子</td>\n    <td class=\"gt_row gt_right\">64</td>\n    <td class=\"gt_row gt_right\">3,324,160</td>\n    <td class=\"gt_row gt_right\">0.563</td>\n    <td class=\"gt_row gt_right\">0.007</td>\n    <td class=\"gt_row gt_right\">1.0</td>\n    <td class=\"gt_row gt_right\">1.2</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">ATOM64_s1</td>\n    <td class=\"gt_row gt_left\">SVD 原子</td>\n    <td class=\"gt_row gt_right\">64</td>\n    <td class=\"gt_row gt_right\">6,400</td>\n    <td class=\"gt_row gt_right\">0.56</td>\n    <td class=\"gt_row gt_right\">0.004</td>\n    <td class=\"gt_row gt_right\">0.96</td>\n    <td class=\"gt_row gt_right\">1.1</td>\n  </tr>\n  <tr>\n    <td class=\"gt_row gt_left\">RAND64_s1</td>\n    <td class=\"gt_row gt_left\">随机正交基</td>\n    <td class=\"gt_row gt_right\">64</td>\n    <td class=\"gt_row gt_right\">6,400</td>\n    <td class=\"gt_row gt_right\">0.549</td>\n    <td class=\"gt_row gt_right\">-0.007</td>\n    <td class=\"gt_row gt_right\">0.94</td>\n    <td class=\"gt_row gt_right\">1.15</td>\n  </tr>\n</tbody>\n\n</table>\n\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n预注册判据 1（ATOM64 vs RAND64，同容量不同基）：Δ = -0.007 ⇒ |Δ| < 噪声带 0.030 ⇒ SVD 原子基并不比随机正交基好：σ 序在此不携带功能信息\n预注册判据 2（ATOM64 ≈ lora8？）：ATOM64 0.523 vs 控制 0.556（Δ -0.033，参数量 7.9k vs 4.4M = 1/550）\n容量维度：ATOMfull（全部 896 个原子，51k 参数 = 控制的 1/86）dev 0.563（Δ +0.007）⇒ 只要原子给够，'只重标已有方向'就能追平 LoRA；而 ATOM64（只给 top-64）掉到 0.523 ⇒ 起作用的是维度，不是'挑对了大原子'\n预注册判据 3（要不要谱外新方向？）：ATOM64_L8 0.523 vs ATOM64 0.523（Δ +0.000）\n判据 1（注意力 q/k/v/o）：ATOM64 0.523 vs RAND64 0.531 ⇒ Δ = -0.007 （噪声带内 ⇒ 原子基无优势），可学参数 7,936（= LoRA r=8 控制的 1/554）\n判据 1（MLP gate/up/down）：ATOM64 0.560 vs RAND64 0.549 ⇒ Δ = +0.011 （噪声带内 ⇒ 原子基无优势），可学参数 6,400（= LoRA r=8 控制的 1/687）\n混淆项已排除：TARGETS=both（注意力+MLP 共 120 个矩阵，自带 lora 控制组）—— lora 0.556（复现 stage9/10/11 的 0.556），ATOM64 0.531 vs RAND64 0.542（Δ -0.011，噪声带内），ATOMfull 0.578（Δ +0.022，参数 72,448 = 控制的 1/60）\n⇒ 三条一起读：能不能训哪些方向 = 维度问题，不是'挑对大原子'的问题；把全部原子的系数都给出去（72k 标量、full-rank 但对角），单 seed 上已经追平/超过 4.4M 参数的 LoRA r=8（dev_loss 更差 1.84 vs 1.13，说明它靠'重标已有方向'硬拟合，泛化仍需复验）。\n```\n:::\n:::\n\n\n# 6. 实验 E（Stage 12）：定向删除 vs 随机删除 vs 按谱位删除\n\n前三节都是\"训练侧\"的证据。这一节是**减法侧**的决定性一刀：先用污染训练流测出\n$\\Delta W$ 的 top-K 右奇异方向（**污染指纹**，K=2 对应 stage10 实测 r_eff≈2.3），\n再回到原始权重，在 W₀ 的 SVD 基里删掉 **同样条数**的原子，三组只差\"删哪几个\"：\n\n| 组 | 删哪些原子 | 坐标 |\n|---|---|---|\n| `TGT` | 与污染指纹最对齐的 K 个原子 | **功能序**（探针定位） |\n| `RAND` | 与 TGT **同分位带**的随机 K 个 | 无坐标（取向随机、能量分布可比） |\n| `SPEC` | 6–10 分位里 σ 最大的 K 个 | **大小序**（我们此前一直在用的那种切法） |\n| `noop` | 不删 | 参照 |\n\n::: {#132ff80a .cell execution_count=8}\n\n::: {.cell-output .cell-output-stdout}\n```\ntgt_minus_rand_f50 {\"delta\": -0.014440433212996373, \"localizable\": false, \"dev_noop\": 0.5270758122743683, \"dev_tgt\": 0.5018050541516246, \"dev_rand\": 0.516245487364621}\nspec_minus_rand_f50 {\"delta\": 0.0072202166064981865}\nany_gain_f50 {\"rand\": -0.010830324909747335, \"spec\": -0.0036101083032491488, \"tgt\": -0.02527075812274371}\n```\n:::\n:::\n\n\n![](/figs/stage12_arms.png)\n\n:::{.callout-warning title=\"⚠️ 探针的混淆项与更干净的版本（PROBE_F=1.0）\"}\n上面用的\"污染指纹\"来自 **f=0.5 的混合流**，那里的 $\\Delta W$ 同时包含**任务学习方向**与**垃圾方向**，\n两者混在一起 ⇒ `TGT` 删掉的其实是\"学习自己要用的方向\"，所以它反而**最差**（−0.025）就不足为奇。\n更干净的对照是**纯垃圾探针**（`PROBE_F=1.0`：只用伪标注句对训练，完全不含干净样本），\n结果在 `outputs/stage12_pure/`（跑法：\n`JUNK_FRACS=0.5 PROBE_F=1.0 ARMS=tgt,rand,spec K=2 python scripts/stage12_targeted_deletion.py`）：\n\n::: {#f70c5c84 .cell execution_count=9}\n\n::: {.cell-output .cell-output-stdout}\n```\n纯垃圾探针下的三组（同一 f=0.5 训练流、同 seed，参照 noop=0.527）：\n  tgt   dev=0.495  Δ vs noop=-0.032\n  rand  dev=0.516  Δ vs noop=-0.011\n  spec  dev=0.523  Δ vs noop=-0.004\nTGT − RAND = -0.022 ⇒ 仍在噪声带内：即便用纯垃圾指纹，污染也不可定点删除\n```\n:::\n:::\n\n\n:::\n\n# 7. 结论\n\n:::{.callout-important title=\"坐标之争的当前判决（本页数字随运行自动更新）\"}\n1. **σ 序携带多少信息，是\"矩阵类型\"的函数**：注意力 rel_perm 0.82–1.04（top-10% σ 占 54–63% 能量），\n   MLP `down_proj` 只有 0.45–0.49（top-10% 占 25%）。本项目 stage1–12 的所有切割都落在**最平**的那一类上\n   ⇒ 效应小（+0.02~+0.03）、等能量后位置残差消失（+0.015）是**结构性的必然**，不是\"假设被否证\"。\n2. **保谱重排是最强的一条正面证据（实验 B）**：保持 σ 多重集 / 能量分布 / Frobenius 范数 / 秩**逐位不变**，\n   只随机打乱\"哪个方向配哪个 σ\"（干预强度 ≈ 改变矩阵 47% 的 Frobenius 质量），\n   RTE 微调成绩**没有可检出的变化**：全局置换 Δ=−0.004、带内置换 Δ=−0.011，均在 ±0.030 噪声带内（seed 1）。\n   ⇒ 对这类平坦矩阵，**\"第几大\"这个坐标本身几乎不携带下游功能信息** —— 用户\"按大小切割欠妥\"在此成立。\n3. **但取向并非完全无关（实验 A）**：把 LoRA 输入侧换成等容量 Haar 随机正交基，\n   dev best 0.538 vs 控制 0.556（**−0.018**；末 3 epoch 均值 −0.011）⇒ 学习自己挑的方向仍略优于随机方向，\n   代价约半个噪声带。与\"存在功能序、但它不等于 σ 序\"一致。\n4. **功能序可以直接测，而且它与 σ 序不相关（实验 C，两类矩阵都测了）**：零训练单方向损伤\n   （pad-masked 语言建模损失）给出 **mean Kendall τ(σ序, 功能序) = −0.22（MLP down_proj）\n   / −0.12（注意力 q_proj）** ⇒ **单个方向越\"大\"并不越重要**。同时：\n   · **整带**尺度上能量序仍然有效（MLP：削 top 带 Δloss +0.319 vs 削 tail 带 +0.008，相差 40 倍）；\n   · 但**深层 L20 最重要的 8 个方向里 0/8 落在 σ 前 10%**（注意力 L20 也只有 2/8，随机期望 0.8/8）。\n   · 值得注意：**q_proj 的谱更陡（rel_perm≈1.0）却与功能序更不相关（τ≈0）**，\n     而 down_proj 的 top 带损伤代价大 6 倍 —— 说明\"谱陡峭度\"与\"功能可定位性\"是**两回事**。\n   ⇒ 这就是\"数据科学按大小排、智能科学按功能排\"的定量版本：**大小序在粗尺度（带）上够用，\n   在细尺度（单个方向）上失效** —— 而我们的 A/B/C、TAIL/MID 切割恰好是在细尺度上做手术。\n5. **两条序都不是最自然的坐标（实验 D / Stage 14 预注册）**：注意力的天然单位是 **rank-1 原子**，\n   甚至必须是 q/k 的**原子对** $(i,j)$（其权重为 $\\sigma^q_i\\sigma^k_j\\,u^{q\\top}_iu^k_j$，推导见\n   `stage/stage14.md`）——即\"重述参数\"应挂在原子上，而不是挂在稠密矩阵的输入/输出半边。\n   预注册预言：`ATOM64` ≫ `RAND64`（同容量）且 `ATOM64` ≈ `lora8`（**550 倍**少的参数）。\n6. **减法侧的判决（实验 E / Stage 12，两种探针都做了）**：在同一污染训练流上删**同样条数**的原子，\n   三套坐标的 best dev（f=0.5、seed1、noop=0.527）：\n\n   | 探针 | TGT | RAND | SPEC |\n   |---|---|---|---|\n   | 混合指纹（f=0.5 流的 ΔW） | 0.502 (−0.025) | 0.516 (−0.011) | 0.523 (−0.004) |\n   | **纯垃圾指纹**（f=1.0 流的 ΔW） | **0.495 (−0.032)** | 0.516 (−0.011) | 0.523 (−0.004) |\n\n   ⇒ **三组全部 ≤ 0，而且\"按污染指纹删\"删得最狠**（TGT−RAND = −0.022）。\n   按预注册判据落第三档：**撤回\"删除式手术能提升泛化\"这条路线，Stage 10 的在线监测才是可继续的方向**。\n   （诚实记录：TGT 删掉的能量 0.37% > RAND 0.25% > SPEC 0.19%，能量未严格配平 ⇒ TGT 的一部分损失是能量损失；\n   但方向上没有任何一组出现\"删了反而更好\"的信号。）\n7. **待办**：实验 A/B 的 seed 3、Stage 12 的能量严格配平版（按 σ² 等量随机选原子）、\n   以及把\"删不动污染\"与\"垃圾写在中带\"合起来重估 Stage 10 的报警统计量（用 mid_E/rel 的联合量）。\n:::\n\n## 复现\n\n```bash\n# §1 谱陡峭度诊断（CPU，~1 分钟）\npython scripts/spectral_steepness.py\n# §2/§3 随机子空间 + 保谱重排（0.5B，单组 4–7 分钟）\nMODEL_PATH=<qwen0.5b> SEEDS=1,2 OUT_DIR=outputs/stage11 \\\n  python scripts/stage11_random_subspace.py lora RS10 SHUFb SHUFg\n# §4 布洛卡式损伤探针（零训练前向）\nLAYERS=0,20 PER_BAND=6 python scripts/two_orderings.py\n# §5 rank-1 原子重参数化\nMODEL_PATH=<qwen0.5b> SEEDS=1 OUT_DIR=outputs/stage14 \\\n  python scripts/stage14_rank1_atoms.py ATOM64 RAND64 ATOMfull ATOM64_L8\n```\n\n",
    "supporting": [
      "atom-coordinates_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}